#!/usr/bin/bash
exec >> cron.log 2>&1

if let $SECONDS/60%4
then
flag=""
else flag="--reprocess"
fi
echo Flag: --$flag


cd /home/john/py/popit3

exec </dev/null >> /home/john/py/popit3/out.log 2>&1

 ./popit3.py $flag

echo RC: $?

exit 0
# # # # #

. /home/john/.bashrcs/api_keys
cd /home/john/py/envoy
exec >> cron.log 2>&1
/usr/bin/python3 orchestrator.py --max-iterations 2

echo RC: $?
